site_name: OpenL Tablets
site_url: https://openl.readthedocs.io/en/latest/
nav:
  - Latest User Guides: 
    - Installation Guide: documentation/guides/installation_guide.md
    - Demo Package Guide: documentation/guides/demo_package_guide.md
    - for Business Users: 
      - Reference Guide: documentation/guides/reference_guide.md
      - WebStudio User Guide: documentation/guides/webstudio_user_guide.md
  - Test: 'test/test01.md'
   
theme: readthedocs

repo_url: https://github.com/EISTW/OpenL/

markdown_extensions:
  - markdown.extensions.admonition
  - toc:
      permalink: True
  
extra_css:
    - css/extra.css
