site_name: OpenL Tablets
site_url: https://openl.readthedocs.io/en/latest/
nav:
  - Latest Guides: documentation/guides/latest_guides.md
  - Previous Guides: documentation/guides/previous_guides.md
  - Test: 'test/test01.md'
  - Test2: documentation/latest_adrian.md
   
theme: readthedocs

repo_url: https://github.com/EISTW/OpenL/

markdown_extensions:
  - markdown.extensions.admonition
  - toc:
      permalink: True
  
extra_css:
    - css/extra.css
